-- ============================================================
-- 寜的小站 Ning's Blog · Supabase 初始化脚本
-- 使用方法：Supabase 控制台 → SQL Editor → New query → 粘贴全部内容 → Run
-- 幂等：可重复执行
-- ============================================================

-- 密码哈希需要 pgcrypto（Supabase 默认安装在 extensions schema）
create extension if not exists pgcrypto with schema extensions;

-- ============ 建表 ============

-- 分类（目录结构，支持嵌套）
create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  description text default '',
  parent_id bigint references public.categories(id) on delete set null,
  sort int default 0,
  created_at timestamptz default now()
);

-- 文章（status: published / draft；private: 仅私人空间可见）
create table if not exists public.posts (
  id bigint generated by default as identity primary key,
  title text not null,
  description text default '',
  content text default '',
  cover text default '',
  tags text default '',
  category_id bigint references public.categories(id) on delete set null,
  private boolean default false,
  pinned boolean default false,
  status text default 'published',
  views int default 0,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);
create index if not exists idx_posts_category on public.posts(category_id);
create index if not exists idx_posts_created on public.posts(created_at desc);

-- 杂谈说说（朋友圈，media 为 jsonb 数组 [{url,name,mime,size}]）
create table if not exists public.talks (
  id bigint generated by default as identity primary key,
  content text not null,
  media jsonb default '[]'::jsonb,
  created_at timestamptz default now()
);

-- 友链
create table if not exists public.links (
  id bigint generated by default as identity primary key,
  name text not null,
  url text not null,
  avatar text default '',
  description text default '',
  sort int default 0,
  created_at timestamptz default now()
);

-- 站点设置（key-value）
create table if not exists public.settings (
  key text primary key,
  value text not null
);

-- 访问统计（每次页面访问一行，按天聚合展示）
create table if not exists public.visits (
  id bigint generated by default as identity primary key,
  day text not null default to_char(now() at time zone 'Asia/Shanghai', 'YYYY-MM-DD'),
  visitor_id text not null,
  created_at timestamptz default now()
);
create index if not exists idx_visits_day on public.visits(day);

-- ============ 行级安全（RLS） ============
-- 核心原则：匿名只能读公开数据；登录（ authenticated ）后可管理一切

alter table public.categories enable row level security;
alter table public.posts     enable row level security;
alter table public.talks     enable row level security;
alter table public.links     enable row level security;
alter table public.settings  enable row level security;
alter table public.visits    enable row level security;

-- categories：匿名可读，登录可管理
drop policy if exists cat_anon_read on public.categories;
create policy cat_anon_read on public.categories for select to anon using (true);
drop policy if exists cat_auth_all on public.categories;
create policy cat_auth_all on public.categories for all to authenticated using (true) with check (true);

-- posts：匿名只能读「已发布且非私密」；登录可管理全部（含草稿/私密）
drop policy if exists post_anon_read on public.posts;
create policy post_anon_read on public.posts for select to anon using (status = 'published' and private = false);
drop policy if exists post_auth_all on public.posts;
create policy post_auth_all on public.posts for all to authenticated using (true) with check (true);

-- talks / links：匿名可读，登录可管理
drop policy if exists talk_anon_read on public.talks;
create policy talk_anon_read on public.talks for select to anon using (true);
drop policy if exists talk_auth_all on public.talks;
create policy talk_auth_all on public.talks for all to authenticated using (true) with check (true);

drop policy if exists link_anon_read on public.links;
create policy link_anon_read on public.links for select to anon using (true);
drop policy if exists link_auth_all on public.links;
create policy link_auth_all on public.links for all to authenticated using (true) with check (true);

-- settings：匿名只能读公开键；登录可管理（密钥哈希绝不外泄）
drop policy if exists set_anon_read on public.settings;
create policy set_anon_read on public.settings for select to anon
  using (key in ('site_name','site_tagline','author','site_start','about_content'));
drop policy if exists set_auth_all on public.settings;
create policy set_auth_all on public.settings for all to authenticated using (true) with check (true);

-- visits：匿名只能插入（统计上报），不能读
drop policy if exists visit_anon_insert on public.visits;
create policy visit_anon_insert on public.visits for insert to anon with check (true);
drop policy if exists visit_auth_insert on public.visits;
create policy visit_auth_insert on public.visits for insert to authenticated with check (true);

-- ============ RPC 函数（security definer，供匿名安全调用） ============

-- 站点统计：PV / UV
create or replace function public.get_site_stats()
returns json language sql security definer set search_path = public as $$
  select json_build_object(
    'pv', (select count(*) from public.visits),
    'uv', (select count(distinct visitor_id) from public.visits)
  )
$$;

-- 访问趋势：按天 PV
create or replace function public.get_visits_trend()
returns jsonb language sql security definer set search_path = public as $$
  select coalesce(jsonb_agg(row_to_json(t) order by t.day), '[]'::jsonb)
  from (
    select day, count(*)::int as pv
    from public.visits group by day
  ) t
$$;

-- 校验私人空间访问码
create or replace function public.verify_private_code(p_code text)
returns boolean language plpgsql security definer set search_path = public, extensions as $$
begin
  return exists (
    select 1 from public.settings
    where key = 'private_code_hash'
      and value = encode(extensions.digest(p_code, 'sha256'), 'hex')
  );
end $$;

-- 私密文章列表（访问码正确时返回）
create or replace function public.get_private_posts(p_code text)
returns setof public.posts language plpgsql security definer set search_path = public, extensions as $$
begin
  if exists (
    select 1 from public.settings
    where key = 'private_code_hash'
      and value = encode(extensions.digest(p_code, 'sha256'), 'hex')
  ) then
    return query select * from public.posts where status = 'published' and private = true order by created_at desc;
  end if;
end $$;

-- 单篇私密文章
create or replace function public.get_private_post(p_code text, p_id bigint)
returns setof public.posts language plpgsql security definer set search_path = public, extensions as $$
begin
  if exists (
    select 1 from public.settings
    where key = 'private_code_hash'
      and value = encode(extensions.digest(p_code, 'sha256'), 'hex')
  ) then
    return query select * from public.posts where id = p_id and private = true and status = 'published';
  end if;
end $$;

-- 阅读量 +1
create or replace function public.increment_post_view(p_id bigint)
returns void language sql security definer set search_path = public as $$
  update public.posts set views = views + 1 where id = p_id and status = 'published'
$$;

grant execute on function public.get_site_stats() to anon, authenticated;
grant execute on function public.get_visits_trend() to anon, authenticated;
grant execute on function public.verify_private_code(text) to anon, authenticated;
grant execute on function public.get_private_posts(text) to anon, authenticated;
grant execute on function public.get_private_post(text, bigint) to anon, authenticated;
grant execute on function public.increment_post_view(bigint) to anon, authenticated;

-- ============ Storage：公开可读、登录可写的 media 桶 ============

insert into storage.buckets (id, name, public)
values ('media', 'media', true)
on conflict (id) do nothing;

drop policy if exists media_public_read on storage.objects;
create policy media_public_read on storage.objects
  for select to public using (bucket_id = 'media');

drop policy if exists media_auth_write on storage.objects;
create policy media_auth_write on storage.objects
  for all to authenticated using (bucket_id = 'media') with check (bucket_id = 'media');

-- ============ 种子数据 ============

insert into public.settings (key, value) values
  ('site_name', '寜的小站'),
  ('site_tagline', '宁静致远 · 记录学习、生活与思考'),
  ('author', 'DBD'),
  ('site_start', '2026-09-13'),
  ('about_content', $about$## 你好，我是寜 👋

欢迎来到**寜的小站 · Ning's Blog**！

这里是我记录学习路线、技术教程、生活杂谈和偶尔思考的地方。

- 📚 **教程**：踩坑总结，干货为主
- 🗺 **学习路线**：我的学习地图
- ✍️ **随笔**：偶尔的思考与感悟
- 💬 **杂谈说说**：我的朋友圈

> 这段介绍可以在 管理端 → 站点设置 → 关于我 中修改。$about$),
  ('private_code_hash', '1213a4c20d7454630b1ecade8b17d16fd8000cee5bb2e07d9045c06f9ff516d9')
on conflict (key) do nothing;
-- 默认私人空间访问码：DBDprivate（请部署后立即在管理端修改！）

insert into public.categories (name, slug, description, parent_id, sort) values
  ('教程', 'jiaocheng', '踩坑总结与技术干货', null, 1),
  ('学习路线', 'xuexiluxian', '我的学习地图', null, 2),
  ('随笔', 'suibi', '偶尔的思考与感悟', null, 3)
on conflict (slug) do nothing;

-- 占位文章 1：来自 Wcowin 博客的教程（可在管理端删除）
insert into public.posts (title, description, content, tags, category_id, private, pinned, status, created_at)
select
  'Homebrew 国内如何自动安装（Mac & Linux）【占位文章，可删除】',
  'Homebrew 国内镜像自动安装脚本教程。这是占位参考内容，稍后可在管理端删除。',
  $post1$**自动脚本（全部国内地址）（复制下面一句脚本到终端中粘贴回车）**

**苹果电脑 常规安装脚本（推荐 完全体 几分钟安装完成）：**

```
/bin/zsh -c "$(curl -fsSL https://gitee.com/cunkai/HomebrewCN/raw/master/Homebrew.sh)"
```

**苹果电脑 极速安装脚本（精简版 几秒钟安装完成）：**

```
/bin/zsh -c "$(curl -fsSL https://gitee.com/cunkai/HomebrewCN/raw/master/Homebrew.sh)" speed
```

> Mac 电脑如何打开终端：`command + 空格` 在聚焦搜索中输入 terminal 回车。

**苹果电脑 卸载脚本：**

```
/bin/zsh -c "$(curl -fsSL https://gitee.com/cunkai/HomebrewCN/raw/master/HomebrewUninstall.sh)"
```

常见错误去[该地址](https://gitee.com/cunkai/HomebrewCN/blob/master/error.md)查看。

---

> 📌 本文是搭建站点时的占位参考文章，摘自 [Wcowin 的博客](https://wcowin.work/)，可在管理端直接删除。$post1$,
  'Mac, Homebrew, 占位',
  (select id from public.categories where slug = 'jiaocheng'),
  false, false, 'published', now() - interval '2 days'
where not exists (select 1 from public.posts where title like 'Homebrew 国内如何自动安装%');

-- 占位文章 2：站点功能介绍（参考阿叶博客，可在管理端删除）
insert into public.posts (title, description, content, tags, category_id, private, pinned, status, created_at)
select
  '欢迎来到寜的小站【占位文章，可删除】',
  '寜的小站 Ning''s Blog 上线啦！这是占位参考内容，稍后可在管理端删除。',
  $post2$# 欢迎使用寜的小站 🎉

**寜的小站 · Ning's Blog** 是一个个人博客系统：前台极简风格、全宽自适应布局；数据存于 Supabase 云数据库；通过 GitHub Pages 免费托管。

## 本站功能

### 前台展示

- **首页**：个人介绍卡片、置顶与最新文章、最近杂谈
- **内容板块**：教程 / 学习路线 / 随笔 / 杂谈说说（可在管理端自由调整目录）
- **杂谈说说**：朋友圈式时间线，支持图片、视频、音频、任意文件
- **友链 & 关于我**
- **私人空间**：输入访问码后，私密文章仅在你的设备可见
- **页脚统计**：运行时长、访问量、访客数
- **反调试保护**：F12 / 控制台等调试操作会被打断

### 后台管理（/admin/）

- 邮箱密码登录（Supabase Auth）
- 数据看板：文章 / 草稿 / 阅读 / PV / UV / 14 天趋势
- 文章发布：Markdown 实时预览、选择分类、置顶、私密、**草稿箱 + 本地自动保存**
- 目录结构管理：分类树增删改、嵌套、排序
- 杂谈发布与图片视频上传
- 友链、文件、站点设置

---

> 📌 本文是搭建站点时的占位参考文章，参考自 [阿叶 Ayeez 博客](https://blog.ayeez.cn)，可在管理端直接删除。$post2$,
  '博客, 占位',
  (select id from public.categories where slug = 'suibi'),
  false, false, 'published', now() - interval '1 day'
where not exists (select 1 from public.posts where title like '欢迎来到寜的小站%');

-- 示例友链
insert into public.links (name, url, avatar, description, sort)
select 'Wcowin 的博客', 'https://wcowin.work/', '', '本站样式灵感来源，感谢！', 1
where not exists (select 1 from public.links where url = 'https://wcowin.work/');

insert into public.links (name, url, avatar, description, sort)
select '阿叶 Ayeez 的博客', 'https://blog.ayeez.cn/', '', '管理端灵感来源，感谢！', 2
where not exists (select 1 from public.links where url = 'https://blog.ayeez.cn/');
